proto_outdir = "./proto"

[[dependencies]]
  target = "github.com/opensaasstudio/plasma/protobuf"
  branch = "master"

[[dependencies]]
  target = "github.com/protocolbuffers/protobuf/src"
  branch = "master"