proto_outdir = "./proto"

[[dependencies]]
  target = "github.com/opensaasstudio/plasma/protobuf"
  branch = "master"
  protocol = "ssh"

[[dependencies]]
  target = "github.com/protocolbuffers/protobuf/src"
  branch = "master"
  ignores = [
    "/google/protobuf/test_messages_proto3",
    "**/util/**/testdata/**",
    "**/protobuf/test_messages_proto2.proto",
  ]
  protocol = "https"

[[dependencies]]
  target = "github.com/protodep/catalog/hierarchy"
  branch = "main"
  includes = [
    "/protodep/hierarchy/service.proto",
    "**/fuga/**",
  ]
  protocol = "https"
